import type { AppState, DayPlan } from "./types";

export const DEFAULT_PLAN: DayPlan[] = [
  {
    id: 1,
    name: "Dzień 1",
    focus: "Klata + brzuch",
    tone: "rose",
    exercises: [
      {
        id: "d1-bench",
        name: "Wyciskanie sztangi na ławce płaskiej",
        setsMin: 4,
        setsMax: 4,
        repsMin: 5,
        repsMax: 8,
      },
      {
        id: "d1-decline-pushup",
        name: "Pompki z nogami na podwyższeniu",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 15,
      },
      {
        id: "d1-shoulder-press",
        name: "Wyciskanie na barki na wyciągu",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 12,
      },
      {
        id: "d1-triceps",
        name: "Prostowanie ramion na wyciągu",
        setsMin: 2,
        setsMax: 3,
        repsMin: 10,
        repsMax: 15,
      },
      {
        id: "d1-curl-db",
        name: "Uginanie ramion z hantlami",
        setsMin: 2,
        setsMax: 3,
        repsMin: 10,
        repsMax: 15,
      },
      {
        id: "d1-hanging-leg",
        name: "Unoszenie nóg w zwisie",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 15,
      },
    ],
  },
  {
    id: 2,
    name: "Dzień 2",
    focus: "Plecy",
    tone: "sky",
    exercises: [
      {
        id: "d2-pullup",
        name: "Podciąganie",
        setsMin: 4,
        setsMax: 4,
        repsMin: 5,
        repsMax: 10,
      },
      {
        id: "d2-cable-row",
        name: "Wiosłowanie na wyciągu",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 12,
      },
      {
        id: "d2-db-row",
        name: "Wiosłowanie hantlem jednorącz",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 12,
      },
      {
        id: "d2-face-pull",
        name: "Face pull na wyciągu",
        setsMin: 2,
        setsMax: 3,
        repsMin: 12,
        repsMax: 15,
      },
      {
        id: "d2-barbell-curl",
        name: "Uginanie ramion ze sztangą",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 12,
      },
    ],
  },
  {
    id: 3,
    name: "Dzień 3",
    focus: "Nogi + brzuch",
    tone: "emerald",
    exercises: [
      {
        id: "d3-squat",
        name: "Przysiady ze sztangą",
        setsMin: 4,
        setsMax: 4,
        repsMin: 5,
        repsMax: 8,
      },
      {
        id: "d3-rdl",
        name: "Rumuński martwy ciąg",
        setsMin: 3,
        setsMax: 3,
        repsMin: 6,
        repsMax: 10,
      },
      {
        id: "d3-split-squat",
        name: "Bulgarian split squat",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 12,
        note: "na nogę",
      },
      {
        id: "d3-calf",
        name: "Wspięcia na palce",
        setsMin: 3,
        setsMax: 3,
        repsMin: 10,
        repsMax: 15,
      },
      {
        id: "d3-crunch",
        name: "Spięcia brzucha na wyciągu",
        setsMin: 3,
        setsMax: 3,
        repsMin: 10,
        repsMax: 15,
      },
    ],
  },
  {
    id: 4,
    name: "Dzień 4",
    focus: "Full body",
    tone: "amber",
    exercises: [
      {
        id: "d4-squat",
        name: "Przysiady ze sztangą",
        setsMin: 3,
        setsMax: 3,
        repsMin: 6,
        repsMax: 8,
      },
      {
        id: "d4-bench",
        name: "Wyciskanie sztangi na ławce płaskiej",
        setsMin: 3,
        setsMax: 3,
        repsMin: 6,
        repsMax: 8,
      },
      {
        id: "d4-pullup",
        name: "Podciąganie",
        setsMin: 3,
        setsMax: 3,
        repsMin: 6,
        repsMax: 10,
      },
      {
        id: "d4-cable-row",
        name: "Wiosłowanie na wyciągu",
        setsMin: 3,
        setsMax: 3,
        repsMin: 8,
        repsMax: 12,
      },
      {
        id: "d4-shoulder-press",
        name: "Wyciskanie na barki na wyciągu",
        setsMin: 2,
        setsMax: 3,
        repsMin: 8,
        repsMax: 12,
      },
      {
        id: "d4-barbell-curl",
        name: "Uginanie ramion ze sztangą",
        setsMin: 2,
        setsMax: 2,
        repsMin: 10,
        repsMax: 12,
      },
      {
        id: "d4-triceps",
        name: "Prostowanie ramion na wyciągu",
        setsMin: 2,
        setsMax: 2,
        repsMin: 10,
        repsMax: 12,
      },
    ],
  },
];

export const EXTRA_EXERCISE_SUGGESTIONS = [
  "Wyciskanie hantli na ławce płaskiej",
  "Wyciskanie na ławce skośnej",
  "Pompki klasyczne",
  "Dip na poręczach",
  "Wyciskanie żołnierskie",
  "Unoszenie hantli bokiem",
  "Martwy ciąg",
  "Ściąganie drążka wyciągu",
  "Hip thrust",
  "Wspięcia na palce siedząc",
  "Plank",
  "Allahy na wyciągu",
];

export function createDefaultState(): AppState {
  return {
    version: 1,
    plan: structuredClone(DEFAULT_PLAN),
    workouts: [],
    activeWorkoutId: null,
  };
}

export function getDay(plan: DayPlan[], dayId: number) {
  return plan.find((day) => day.id === dayId) ?? null;
}
